service: ${env:SERVICE_NAME}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-env-generator
  - serverless-plugin-monorepo

package:
  exclude:
    - '**/__fixtures__/**'
    - fixtures/**
    - seeders/**
    - '**/__tests__/**'
    - '**/__mocks__/**'
    - aws.config.yml
    - backlog.todo
    - environment.yml
    - index.js
    - jest.config.js
    - package.json
    - README.md
    - yarn-error.log

custom:
  envFiles: # for serverless-env-generator plugin
    - environment.yml
  envEncryptionKeyId: ${file(aws.config.yml):KMS_KEY_ID}
  serverless-offline:
    port: ${env:PORT}
  awsConfig: ${file(aws.config.yml):${opt:stage, 'development'}}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  profile: hawaii.js
  region: ${opt:region, 'eu-north-1'}
  usagePlan: ${self:custom.awsConfig.LAMBDA.USAGE_PLAN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${env:DB_USERS_TABLE_NAME}"

functions:
  app:
    handler: serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  v1-create:
    handler: serverless.handler
    events:
      - http: 'POST v1/users'
  v1-find:
    handler: serverless.handler
    events:
      - http: 'GET v1/users'

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${env:DB_USERS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.awsConfig.DYNAMODB.USERS_TABLE.TABLE_THROUGHPUT}
        GlobalSecondaryIndexes:
          - IndexName: idGlobalIndex
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput: ${self:custom.awsConfig.DYNAMODB.USERS_TABLE.ID_GLOBAL_INDEX_THROUGHPUT}
